esphome:
  name: "bleproxy-via-uart"
  friendly_name: "BLE Proxy Via UART"
  project:
    name: "Sengled.E39-G8C"
    version: "1.0.0"
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    then:
      - lambda: |-
          App.set_loop_interval(2);

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

api:
  port: 6053

mdns:
  disabled: true

network:
  enable_ipv6: false

uart:
  id: uart_ble
  tx_pin: GPIO7
  rx_pin: GPIO6
  baud_rate: 230400
  rx_buffer_size: 1024

esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:
  active: false
  connection_slots: 4

logger:
  baud_rate: 0
#  level: DEBUG

external_components:
  - source:
      type: local
      path: components
    components: [uart_api]


uart_api:
  id: uart_bridge
  uart_id: uart_ble
  api_port: 6053
  rx_buffer_size: 512
  debug_echo: false

ota:
  platform: esphome
  port: 3232

switch:
  - platform: template
    id: ota_mode_switch
    name: "OTA Mode"
    optimistic: true
    internal: false
    on_turn_on:
      - lambda: id(uart_bridge).set_ota_mode(true);
    on_turn_off:
      - lambda: id(uart_bridge).set_ota_mode(false);

output:
  - platform: gpio
    id: led
    pin: GPIO8
    inverted: true

light:
  - platform: binary
    id: led_light
    output: led
    internal: true
    restore_mode: ALWAYS_OFF

interval:
  - interval: 200ms
    then:
      - if:
          condition:
            lambda: 'return id(ota_mode_switch).state;'
          then:
            - light.toggle: led_light
  - interval: 1000ms
    then:
      - if:
          condition:
            lambda: 'return !id(ota_mode_switch).state;'
          then:
            - light.toggle: led_light
